const METINLER = {
  tr: {
    kullanim: 'kod tabanindan canli mimari haritasi',
    komutlar: 'komutlar',
    secenekler: 'secenekler',
    k_ciz: 'haritayi uret ve ac',
    k_tara: 'ham grafi kaydet',
    k_anlat: 'bir dugumu acikla: rol, cagiranlar, bagimliliklar',
    k_yol: 'iki dugum arasindaki en kisa zinciri bul',
    k_denetle: 'saglik raporu: donguler, tanri dugumler, riskli dosyalar',
    k_kume: 'baglantiya gore topluluk bul, klasorlerle karsilastir',
    k_disaaktar: 'dot | graphml | csv | mermaid | json',
    k_fark: 'iki tarama arasindaki degisim',
    k_izle: 'dosya degistikce haritayi tazele',
    s_cikti: 'cikti yolu (varsayilan cikti/<ad>.html)',
    s_gorunum: 'paket (varsayilan), dosya ya da simge seviyesi',
    s_derinlik: 'grup yolu derinligi (varsayilan 2)',
    s_gruplama: 'gruplari klasore gore mi baglantiya gore mi kur',
    s_odak: 'o dugumun komsulugunu ciz',
    s_cevre: 'odak yaricapi (varsayilan 1)',
    s_enfazla: 'cizilecek en fazla dugum (varsayilan 120)',
    s_yon: 'akis yonu (varsayilan sag)',
    s_tema: 'acilis temasi',
    s_dis: 'dis paketleri de ciz (varsayilan disarida)',
    s_testyok: 'test dosyalarini disla',
    s_gun: 'git gecmisi penceresi, gun (varsayilan 180)',
    s_gecmisyok: 'git gecmisi katmanini okuma',
    s_konum: 'kaydedilmis dugum konumlarini uygula',
    s_hepsi: 'simge gorunumunde bagsiz simgeleri de ciz',
    s_json: 'cozumleme ciktisini JSON ver',
    s_acma: 'uretince tarayicida acma',
    s_dil: 'cikti dili: tr | en',
    ozet_graf: (a, b, c) => `${a} dosya, ${b} bag, ${c} dongu`,
    ozet_cizim: (a, b, c) => `cizim: ${a} dugum, ${b} katman, ${c} kesisme`,
    ozet_tara: (a, b, y) => `${a} dosya, ${b} bag -> ${y}`,
    ozet_disaaktar: (a, b, y) => `${a} dugum, ${b} bag -> ${y}`,
    hata_yol: y => 'yol bulunamadi: ' + y,
    hata_klasor: y => 'bir klasor bekleniyordu: ' + y,
    hata_graf: y => 'graf dosyasi bulunamadi: ' + y,
    hata_kaynak: y => `${y} altinda taranacak kaynak dosya yok.`,
    hata_uzanti: u => '  desteklenen uzantilar: ' + u,
    hata_deger: (a, d) => `--${a} icin gecersiz deger: ${d}`,
    hata_bayrak: a => `bilinmeyen secenek: --${a}`,
    hata_gecerli: l => '  gecerli: ' + l,
    hata_sayi: (a, d) => `--${a} bir sayi olmali: ${d}`,
    hata_bicim: l => 'bilinmeyen bicim, gecerli: ' + l,
    hata_odak: t => 'odak bulunamadi: ' + t,
    hata_eslesme: t => 'eslesme yok: ' + t,
    esit_eslesme: (n, t, s) => `"${t}" icin ${n} esit eslesme, secilen: ${s}`,
    digerleri: l => '  digerleri: ' + l,
    izleniyor: 'izleniyor, cikmak icin Ctrl+C',
    tazeleme_hatasi: m => 'tazeleme hatasi: ' + m,
    yol_yok: (a, b) => `${a} -> ${b}: yol yok`,
    yonsuz_ipucu: ' (yonsuz denemek icin --yonsuz)',
    arayuz: {
      g_grup: 'paket görünümü', g_dosya: 'dosya görünümü', g_simge: 'simge görünümü',
      dugum: 'düğüm', bag: 'bağ', dongu: 'döngü', disPaket: 'dış paket', yalniz: 'yalnız',
      ara: 'ara  /  →  dosya, klasör, simge', eslesmeYok: 'eşleşme yok',
      sigdir: 'sığdır', tema: 'tema', gruplar: 'gruplar', tumu: 'tümü', bagTuru: 'bağ türü',
      akis: 'akış', donguler: 'döngüler', degisim: 'değişim', disPaketler: 'dış paketler',
      kaydet: 'kaydet', kisayollar: 'kısayollar',
      cagiran: 'çağıran', bagimlilik: 'bağımlılık', dosya: 'dosya', satir: 'satır',
      simgeler: 'Simgeler', kullananlar: 'Bunu kullananlar', kullandiklari: 'Bunun kullandıkları',
      editorde: 'editörde aç', odakla: 'odakla', yok: 'yok',
      degisiklikPencere: 'değişiklik / 180 gün', yazar: 'yazar', gunOnce: 'gün önce',
      k_ara: 'ara', k_sigdir: 'ekrana sığdır', k_grup: 'grup panelini aç/kapat',
      k_tema: 'sonraki · önceki tema', k_akis: 'akış animasyonu', k_dongu: 'döngüleri izole et',
      k_yakin: 'yakınlaştır · uzaklaştır · sığdır', k_sec: 'seçimi bırak', k_yardim: 'bu pencere',
      ipucu: 'düğümü sürüklersen konumu değişir, <b>kaydet</b> ile dışa aktarılır ve <code>--konum</code> ile geri yüklenir.',
      b_konum: 'konum güncellendi — kaydet ile dışa aktar',
      b_kaydedildi: 'konumlar kaydedildi', b_png: 'PNG indirildi', b_svg: 'SVG indirildi',
      b_pngHata: 'PNG üretilemedi, SVG kullanın', b_donguYok: 'döngü yok',
      b_donguKenar: n => n + ' döngü kenarı', b_gecmisYok: 'git geçmişi okunamadı',
      b_isiAcik: 'renk: son 180 günde değişiklik sayısı', b_isiKapali: 'ısı katmanı kapandı',
      b_tazelendi: 'harita tazelendi, görünüm korundu', b_tema: t => 'tema: ' + t,
      gruplanmamis: '(gruplanmamış)',
      kenar: { 'ice-aktarim': 'içe aktarım', 'dis-bagimlilik': 'dış bağımlılık', cagri: 'çağrı', referans: 'referans', metot: 'metot', icerir: 'içerir' }
    },
    rol: 'rol', kararsizlik: 'kararsizlik', dongude: 'DONGUDE',
    roller: {
      'ara katman': 'ara katman', 'giris noktasi': 'giris noktasi',
      'yaprak / yardimci': 'yaprak / yardimci', 'yalniz': 'yalniz',
      'paylasilan cekirdek': 'paylasilan cekirdek', 'orkestrator': 'orkestrator'
    },
    gecmis: (d, y) => `gecmis: ${d} degisiklik, ${y} yazar`,
    cagiranlar: 'cagiranlar', bagimliliklar: 'bagimliliklar', simgeler: 'simgeler',
    adim: 'adim', dis: 'dis',
    r_ozet: (d, k, s) => `${d} dosya, ${k} bag, ${s} satir`,
    r_uyarilar: 'uyarilar',
    r_dongu: n => `dairesel bagimlilik (${n} kume)`,
    r_tanri: 'en bagli dugumler',
    r_kirilgan: 'hem cagrilan hem cok baglanan (kirilgan)',
    r_degisen: 'en cok degisenler',
    r_zincir: n => `en uzun bagimlilik zinciri: ${n} adim`,
    r_yalniz: 'yalniz dosyalar',
    r_topluluk: n => `${n} topluluk`,
    r_klasore: n => `${n} klasore dagilmis`,
    r_tek_klasor: 'tek klasor',
    r_daha: n => `    ... ${n} dosya daha`,
    u_dongu: n => `${n} dairesel bagimlilik kumesi`,
    u_tanri: n => `${n} dugum ortanca derecenin 3 katindan fazla bagli`,
    u_yalniz: n => `${n} dosya hicbir seye bagli degil`,
    u_riskli: n => `${n} dosya hem cok degisiyor hem cok cagriliyor`,
    f_ozet: (e, s, d) => `+${e} dosya  -${s} dosya  ~${d} degisti`,
    f_kenar: (e, s) => `+${e} bag  -${s} bag`
  },
  en: {
    kullanim: 'a live architecture map from a codebase',
    komutlar: 'commands',
    secenekler: 'options',
    k_ciz: 'build the map and open it',
    k_tara: 'dump the raw graph',
    k_anlat: 'explain one node: role, callers, dependencies',
    k_yol: 'shortest chain between two nodes',
    k_denetle: 'health report: cycles, god nodes, risky files',
    k_kume: 'find communities by connectivity, compare to folders',
    k_disaaktar: 'dot | graphml | csv | mermaid | json',
    k_fark: 'diff two scans',
    k_izle: 'rebuild on file change',
    s_cikti: 'output path (default cikti/<name>.html)',
    s_gorunum: 'package (default), file or symbol level',
    s_derinlik: 'grouping path depth (default 2)',
    s_gruplama: 'group by folder, or by what the code connects',
    s_odak: "draw only that node's neighbourhood",
    s_cevre: 'focus radius (default 1)',
    s_enfazla: 'max nodes drawn (default 120)',
    s_yon: 'flow direction (default right)',
    s_tema: 'starting theme',
    s_dis: 'include external packages (excluded by default)',
    s_testyok: 'drop test files',
    s_gun: 'git history window in days (default 180)',
    s_gecmisyok: 'skip the git history layer',
    s_konum: 'restore saved node positions',
    s_hepsi: 'in symbol view, draw unconnected symbols too',
    s_json: 'emit analysis output as JSON',
    s_acma: 'do not open a browser afterwards',
    s_dil: 'output language: tr | en',
    ozet_graf: (a, b, c) => `${a} files, ${b} edges, ${c} cycles`,
    ozet_cizim: (a, b, c) => `drawn: ${a} nodes, ${b} layers, ${c} crossings`,
    ozet_tara: (a, b, y) => `${a} files, ${b} edges -> ${y}`,
    ozet_disaaktar: (a, b, y) => `${a} nodes, ${b} edges -> ${y}`,
    hata_yol: y => 'path not found: ' + y,
    hata_klasor: y => 'expected a directory: ' + y,
    hata_graf: y => 'graph file not found: ' + y,
    hata_kaynak: y => `no source files to scan under ${y}.`,
    hata_uzanti: u => '  supported extensions: ' + u,
    hata_deger: (a, d) => `invalid value for --${a}: ${d}`,
    hata_bayrak: a => `unknown option: --${a}`,
    hata_gecerli: l => '  valid: ' + l,
    hata_sayi: (a, d) => `--${a} must be a number: ${d}`,
    hata_bicim: l => 'unknown format, valid: ' + l,
    hata_odak: t => 'focus not found: ' + t,
    hata_eslesme: t => 'no match: ' + t,
    esit_eslesme: (n, t, s) => `${n} equal matches for "${t}", picked: ${s}`,
    digerleri: l => '  others: ' + l,
    izleniyor: 'watching, Ctrl+C to stop',
    tazeleme_hatasi: m => 'rebuild failed: ' + m,
    yol_yok: (a, b) => `${a} -> ${b}: no path`,
    yonsuz_ipucu: ' (try --undirected)',
    arayuz: {
      g_grup: 'package view', g_dosya: 'file view', g_simge: 'symbol view',
      dugum: 'nodes', bag: 'edges', dongu: 'cycles', disPaket: 'external', yalniz: 'orphans',
      ara: 'search  /  →  files, folders, symbols', eslesmeYok: 'no match',
      sigdir: 'fit', tema: 'theme', gruplar: 'groups', tumu: 'all', bagTuru: 'edge type',
      akis: 'flow', donguler: 'cycles', degisim: 'churn', disPaketler: 'external',
      kaydet: 'save', kisayollar: 'shortcuts',
      cagiran: 'callers', bagimlilik: 'depends on', dosya: 'files', satir: 'lines',
      simgeler: 'Symbols', kullananlar: 'Used by', kullandiklari: 'Uses',
      editorde: 'open in editor', odakla: 'focus', yok: 'none',
      degisiklikPencere: 'changes / 180 days', yazar: 'authors', gunOnce: 'days ago',
      k_ara: 'search', k_sigdir: 'fit to screen', k_grup: 'toggle group panel',
      k_tema: 'next · previous theme', k_akis: 'flow animation', k_dongu: 'isolate cycles',
      k_yakin: 'zoom in · out · fit', k_sec: 'clear selection', k_yardim: 'this panel',
      ipucu: 'drag a node to move it, <b>save</b> exports the positions and <code>--positions</code> restores them.',
      b_konum: 'position changed — export it with save',
      b_kaydedildi: 'positions saved', b_png: 'PNG downloaded', b_svg: 'SVG downloaded',
      b_pngHata: 'PNG failed, use SVG', b_donguYok: 'no cycles',
      b_donguKenar: n => n + ' cycle edges', b_gecmisYok: 'git history unavailable',
      b_isiAcik: 'colour: changes in the last 180 days', b_isiKapali: 'churn layer off',
      b_tazelendi: 'map rebuilt, view kept', b_tema: t => 'theme: ' + t,
      gruplanmamis: '(ungrouped)',
      kenar: { 'ice-aktarim': 'import', 'dis-bagimlilik': 'external', cagri: 'call', referans: 'reference', metot: 'method', icerir: 'contains' }
    },
    rol: 'role', kararsizlik: 'instability', dongude: 'IN A CYCLE',
    roller: {
      'ara katman': 'middle layer', 'giris noktasi': 'entry point',
      'yaprak / yardimci': 'leaf / helper', 'yalniz': 'orphan',
      'paylasilan cekirdek': 'shared core', 'orkestrator': 'orchestrator'
    },
    gecmis: (d, y) => `history: ${d} changes, ${y} authors`,
    cagiranlar: 'callers', bagimliliklar: 'dependencies', simgeler: 'symbols',
    adim: 'steps', dis: 'external',
    r_ozet: (d, k, s) => `${d} files, ${k} edges, ${s} lines`,
    r_uyarilar: 'warnings',
    r_dongu: n => `circular dependencies (${n} clusters)`,
    r_tanri: 'most connected nodes',
    r_kirilgan: 'both depended on and heavily depending (fragile)',
    r_degisen: 'most changed',
    r_zincir: n => `longest dependency chain: ${n} steps`,
    r_yalniz: 'orphan files',
    r_topluluk: n => `${n} communities`,
    r_klasore: n => `spread over ${n} folders`,
    r_tek_klasor: 'single folder',
    r_daha: n => `    ... ${n} more files`,
    u_dongu: n => `${n} circular dependency clusters`,
    u_tanri: n => `${n} nodes wired above 3x the median degree`,
    u_yalniz: n => `${n} files connected to nothing`,
    u_riskli: n => `${n} files both change often and are depended on`,
    f_ozet: (e, s, d) => `+${e} files  -${s} files  ~${d} changed`,
    f_kenar: (e, s) => `+${e} edges  -${s} edges`
  }
};

export function dilSec(istenen) {
  if (istenen === 'tr' || istenen === 'en') return istenen;
  const cevre = process.env.TG_DIL || process.env.LC_ALL || process.env.LC_MESSAGES || process.env.LANG || '';
  return /^tr/i.test(cevre) ? 'tr' : 'en';
}

export function metinler(dil) {
  return METINLER[dil] || METINLER.en;
}
